### ISSUE TITLE
Is this plugin still maintained? Compatible with piwigo 12.3.0?

### ISSUE THREAD

**Issue by jdaviescoates** [Piwigo/Flickr2Piwigo#63]
Hi there,

I'd really love to use this plugin to import my Flickr photos into my new self-hosted instance of Piwigo but I notice on this page:

https://piwigo.org/ext/extension_view.php?eid=612

It says it's only compatible with version 11 - are there any plans to make it compatible with piwigo 12.3.0?

Thanks!

**Comment by jdaviescoates** [comment]
OK, great, thanks for the update @samwilson! :smile:  :pray: 

Fingers and toes crossed you'll find the time sometime soon to fix things here!:crossed_fingers:

**Comment by fncll** [comment]
Any thoughts on when the plugin might be updated? I'm trying to cobble together some fixes from issues here but it I'm still struggling 😄

**Comment by samwilson** [comment]
Sorry, I'm not sure. I *think* we're pretty much ready to release version 5 of the PhpFlickr library, and so the next step after that would be to upgrade that in the plugin here.

**Comment by glkeswick** [comment]
Hi - I know that technically flickr2piwigo isn't listed as compatible with the current version of Piwigo  13.6.0 but I thought I'd give it a try anyway. In the absence of any installation instructions here's what I've done to try to get it installed:

1. Downloaded the code from https://piwigo.org/ext/extension_view.php?eid=612. 
2. Unzipped the files to a folder  flickr2piwigo and uploaded that folder to the same folder as Piwigo on my host, namely htdocs/photos
3. Pasted the contents of main.inc.php into the Personal Plugin tab in the Piwigo LocalFiles Editor plug-in and saved it.
4.The Flickr2Piwigo appeared in the Plugins list and I was able to activate it.
5. When I go to Photos > Add I see an error message _"Flickr2Piwigo folder name is incorrect, uninstall the plugin and rename it to "flickr2piwigo"_

The hosting service I am using tells me I must put all my stuff under the /htdocs folder they provide. I tried moving the flickr2piwigo folder out of /photos and directly beneath /htdocs but that didn't solve it.

Where do I need to put the Flickr2Piwigo files I downloaded?  Or is this just a sign that it's not going to work with the current version of Piwigo?

Thanks

Andy

**Comment by keanenwold** [comment]
Thanks for the efforts to keep this plugin going @samwilson!!

**Comment by glkeswick** [comment]
Update - I discovered where the Flickr2Piwigo files go. Under the folder in which Piwigo is installed there is a sub-folder called - surprise! - /plugins. So in my case the full path is 

/htdocs/photos/plugins/flickr2piwigo

where /htdocs is required by my hosting service provider, /photos is my Piwigo installation folder and /plugins is where all plug ins have to go and /flickr2piwigo is of course the folder for this particular plug in.

With all that done I then had to track down the Callback URL which is not displayed on the Piwigo configuration pages as described in the instructions. I found anothet post somewhere which said it should look like this:

http://<your piwigo domain>/admin.php?page=plugin-flickr2piwigo-import

so I added that.

Now with the plug-in installed and the Flickr API keys obtained when I click on Import in the plug-in I do get prompted to log-in to Flickr but my log-in is rejected. I think that is because my domain does not currently have an SSL certificate so I've requested one and am just waiting for the CNAME record to propagate to the nameservers.

I'll update this thread again when I have any more progress to report.

**Comment by glkeswick** [comment]
Success!

After I installed an SSL certificate I was able to launch the plugin, login and authorize it to retrieve photos from a test Flickr account.

I am working with a very small set of 4 albums and 14 photographs on Flickr for testing and evaluation purposes, so the first transfer I did was to import all my photos with the option to re-create the Flickr albums from which they originated. It worked like a dream with all photos imported and all albums created. It was pretty quick too although obviously it was a very small set.

During the transfer there were many warning messages displayed which are undecipherable by anybody who, like me, can't read and understand the plugin code, but I have an idea from some of the wording that they are in some way related to null values in imported metadata elements. That might be a problem for some people but probably not in my case although I need to check out if anything important got dropped.

So thanks again to @samwilson and others who developed this plugin. The alternative of eventually downloading and uploading 45000+ photos and manually recreating the source albums is none too appealing. I'll be keeping an eye out for a new version of the plugin too

**Comment by samwilson** [comment]
I am finally getting around to looking at this. I've opened #65 to upgrade the PhpFlickr package, and #66 and #64 as little tidying-ups for things I noticed. I'm having some issues running the latest Piwigo in my local dev environment (partly just because of https://github.com/Piwigo/Piwigo/issues/1845 ) but I'm switching to Docker to resolve some of those, so hopefully will be able to fix the remaining problems with Flickr2Piwigo soon.

**Comment by glkeswick** [comment]
That's awesome Sam, Thank you!

Andy

**Comment by keanenwold** [comment]
Any chance there will be a fix for those of us interested in Piwigo 14? Thanks for all the effort.

**Comment by samwilson** [comment]
The above patches are waiting for review. I'm not a maintainer here, so can't merge them. (I guess I used to be, but am now not because I've been inactive for a long time!)

**Comment by plegall** [comment]
@samwilson I updated the settings of this repository to let you have permissions to merge this pull-request :-D

**Comment by samwilson** [comment]
Oh cool, thanks!

**Comment by samwilson** [comment]
@plegall Are GitHub Actions enabled for this repository? It looks like they're maybe not.

**Comment by keanenwold** [comment]
Thanks all!

**Comment by ClaudiaLev** [comment]
The plugin is very helpful for me, so it would be wonderful, if it will be fixed! Thanks!

**Comment by samwilson** [comment]
Okay, I've tagged and released version 1.5.6 with the above changes. There are still a few improvements I'll try to make, but the basic compatibility with PHP 8.2 should be okay. But of course, please shout as soon as you notice anything wrong!

**Comment by ClaudiaLev** [comment]
Thanks a lot for updating, I am very happy about this.

The new version is listed in the extensions-tab on the piwigo-website, but the new version wasn´t shown on my personal piwigo-website, although the extension is activated on this site.

I had to install it as a new extension and the old one was overwritten.
Now it works very fine!

**Comment by samwilson** [comment]
@ClaudiaLev that's strange, I'm not sure what would cause that. As far as I know, the metadata and packaging of the new version is the same as previous ones. Oh well, I'm glad you got it working!
